# spring
spring.application.name=social-media
spring.jackson.mapper.accept-case-insensitive-enums=true
# spring data
spring.datasource.username=postgres
spring.datasource.password=2435
spring.datasource.url=jdbc:postgresql://localhost/social-media
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
# security
app.cors=http://localhost
app.cors.allowed.methods=GET,POST,PUT,DELETE,PATCH
app.cors.allowed.headers=Content-Type,Authorization
app.cors.allowed.pattern=/**
app.public.endpoints=/login,/signup
# logging
logging.pattern.level="%5p [%X{transactionId}]"
